[project]
name = "Stain Normalization"
version = "0.1.0"
authors = ["Adam Lopatka"]
requires-python = ">=3.11"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "lightning>=2.0.0",
    "albumentations>=1.4.14",
    "torchmetrics>=1.4.14",
    "torchvision>=0.17.2",
    "torch>=2.2.2",
    "tqdm>=4.66.5",
    "rationai-mlkit @ git+https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git",
    "rationai-masks @ git+https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git",
    "rationai-tiling @ git+https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git",
    "rationai-kube-jobs @ git+ssh://git@gitlab.ics.muni.cz/rationai/digital-pathology/libraries/kube-jobs.git",
    "scikit-image>=0.25.2",
    "openslide-bin>=4.0.0.6",
    "rationai-staining @ git+ssh://git@gitlab.ics.muni.cz/rationai/digital-pathology/libraries/staining.git"
]

[tool.pdm.dev-dependencies]
dev = ["mypy", "pre-commit", "ruff"]

[tool.pdm.scripts]
mask_generate = "python preprocessing/mask_generator.py"
tiler = "python preprocessing/tiler.py"

train = "python -m stain_normalization mode=fit"
validate = "python -m stain_normalization mode=validate"
test = "python -m stain_normalization mode=test"
predict = "python -m stain_normalization mode=predict"
l = { composite = ["lint", "format", "mypy"] }
lint = "ruff check --fix"
format = "ruff format"
mypy = "mypy ."
# post_install = { composite = [
#    "pre-commit autoupdate",
#    "pre-commit install",
#    "pre-commit install --hook-type commit-msg",
#] }

[tool.pdm]
distribution = false
