[pytest]
markers = 
    color_conversion: tests expected values and method behavior of the ColorConversion Enum
    stain_separation: tests expected behavior of the stain separation functionality
    stain_reconstruction: tests that applying color combination after color separation return yields roughly the same image
    stain_estimator: tests stain estimation functionality